// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC34v0ENvCsDRHv6ttcKKUHFFhU80RBbjA',
    appId: '1:622391599624:web:f41f31c3cf6be59c5427bd',
    messagingSenderId: '622391599624',
    projectId: 'takopedia-24e8b',
    authDomain: 'takopedia-24e8b.firebaseapp.com',
    databaseURL: 'https://takopedia-24e8b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'takopedia-24e8b.appspot.com',
    measurementId: 'G-7V01NVT14X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9GF63KPo0B-QiIeVPnLX0_JZx9Uhg8z4',
    appId: '1:622391599624:android:38a643363d8d66915427bd',
    messagingSenderId: '622391599624',
    projectId: 'takopedia-24e8b',
    databaseURL: 'https://takopedia-24e8b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'takopedia-24e8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj6HqmHBtC7Wm_vOHcHMiAH5G9YSKyxtE',
    appId: '1:622391599624:ios:217948a68862445d5427bd',
    messagingSenderId: '622391599624',
    projectId: 'takopedia-24e8b',
    databaseURL: 'https://takopedia-24e8b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'takopedia-24e8b.appspot.com',
    iosBundleId: 'com.example.takopedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj6HqmHBtC7Wm_vOHcHMiAH5G9YSKyxtE',
    appId: '1:622391599624:ios:217948a68862445d5427bd',
    messagingSenderId: '622391599624',
    projectId: 'takopedia-24e8b',
    databaseURL: 'https://takopedia-24e8b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'takopedia-24e8b.appspot.com',
    iosBundleId: 'com.example.takopedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC34v0ENvCsDRHv6ttcKKUHFFhU80RBbjA',
    appId: '1:622391599624:web:0c14079de9d4bf195427bd',
    messagingSenderId: '622391599624',
    projectId: 'takopedia-24e8b',
    authDomain: 'takopedia-24e8b.firebaseapp.com',
    databaseURL: 'https://takopedia-24e8b-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'takopedia-24e8b.appspot.com',
    measurementId: 'G-BVPJGDVN5F',
  );
}
